### ISSUE TITLE
Project Delivery: Kickoff Meeting Template

### ISSUE THREAD

**Issue by tanyapowell** [womenhackfornonprofits/whfnp-wiki#1]
## What is a kickoff meeting?
- Purpose of meeting
- Meeting's format
- post its/ pens/ suggested cafes/ remote access (skype/google hangouts/appear in)
- what is the meeting's deliverable?
- What's next for the project?
- What is the project lead's role?
## What is the problem the project is trying to solve?
- how do we break this down
- what are ideal timeframes
- what can WHFNP do 
- book in another f2f session where team can plan first milestone
- MUST create a github repo and add all decisions to the wiki

**Comment by krissy** [comment]
To be added to https://github.com/womenhackfornonprofits/whfnp-wiki/wiki/Project-Delivery-Guidelines-(Pitch-to-Retrospective)
