### ISSUE TITLE
Update completed projects page

### ISSUE THREAD

**Issue by tanyapowell** [womenhackfornonprofits/whfnp-wiki#6]

**Comment by lili2311** [comment]
Updated: https://github.com/womenhackfornonprofits/whfnp-wiki/wiki/Completed-Projects

**Comment by tanyapowell** [comment]
The format between [current projects](https://github.com/womenhackfornonprofits/whfnp-wiki/wiki/Current-Projects) and [completed projects](https://github.com/womenhackfornonprofits/whfnp-wiki/wiki/Completed-Projects) are completely different and they should look the same, but with different content

**Comment by lili2311** [comment]
fixed!
